backend:
  name: git-gateway
  branch: master
  
publish_mode: editorial_workflow
media_folder: static/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: methods
    label: UX Methods
    label_singular: UX Method
    folder: content/methods
    create: true
    slug: {{slug}}
    preview_path: {{slug}}
    fields:
      - { label: Method Title, name: method-title, widget: string }
      - { label: Featured Image, name: method-thumbnail, widget: image }
      - {
          label: Intro,
          name: method-intro,
          widget: markdown,
          required: false,
        }
      - label: Definition
        name: method-definition
        widget: object
        fields:
          - {
              label: Title,
              name: definition-title,
              widget: string,
              default: What is a {{title}}?,
            }
          - { label: Text, name: definition-text, widget: markdown }
          - { label: Image, name: definition-image, widget: image }
      - label: Needs
        name: method-needs
        widget: object
        fields:
          - {
              label: Title,
              name: needs-title,
              widget: string,
              default: What do you need for a {{title}}?,
            }
          - { label: Time items, name: needs-time, widget: markdown }
          - {
              label: Materials items,
              name: needs-materials,
              widget: markdown,
            }
      - label: Steps
        name: method-steps
        widget: object
        fields:
          - {
              label: Title,
              name: steps-title,
              widget: string,
              default: How do you run a {{title}}?,
            }
          - { label: Image, name: steps-image, widget: image }
          - label: Steps List
            name: steps-list
            widget: list
            fields:
              - label: Step
                name: steps-item
                widget: object
                fields:
                  - {
                      label: Title,
                      name: step-title,
                      widget: string,
                      default: What do you need for a {{title}}?,
                    }
                  - { label: Text, name: step-text, widget: markdown }
      - label: Tips
        name: method-tips
        widget: object
        fields:
          - {
              label: Title,
              name: tips-title,
              widget: string,
              default: Tips for a great {{title}}?,
            }
          - { label: Text, name: tips-text, widget: markdown }
          - { label: Image, name: tips-image, widget: image }
      - label: Resources
        name: method-tips
        widget: list
        fields:
          - { label: Resource, name: resource, widget: markdown }
